spring:
  datasource:
    url: jdbc:oracle:thin:@10.90.1.105:1521/DEV
    username: HR
    password: HR
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
       ddl-auto: update  
       
  application:
    name: MicroService-1   

server:
  port: 5050
  
  
eureka:
  client:  
    fetch-registry: true 
    register-with-eurka: true
    service-url:
      defaultZone: http://localhost:8770/eureka
      
management:    
  endpoints:
    web:
      exposure:
        include:
         - "*"