spring:
  datasource:
    url: jdbc:oracle:thin:@10.90.1.107:1521/SIT
    username: HR
    password: HR
    
  application:
     name: cab-driver-service
  
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true  
server:
   port: 6067  